#!/bin/sh
# $Id: mk-mbst,v 1.2 2020-09-06 22:45:43-07 - - $
cid -is $0 mb2mbst.perl mbint.st
for mb in mb-programs.d/*.mb
do
   mb2mbst.perl $mb
done
mv *.mbst ../.score
for mbst in ../.score/*.mbst
do
   ln -s $mbst
done
