#!/bin/sh
# $Id: mk-tests,v 1.3 2020-09-06 19:54:34-07 - - $
cid -is $0
[ ! -d tmp ] && mkdir tmp
for i in *.mbir
do
   echo mbir.scm $i
   if [ -f $i.in ];
   then
      cat $i.in | mbir.scm $i >tmp/$i.out 2>tmp/$i.err
   else
      mbir.scm $i >tmp/$i.out 2>tmp/$i.err
   fi

done
